import { RESOURCE_URI } from 'shared/constants/global';
import { TaletsOfClassType } from 'shared/constants/talentsData';

export const warrior: TaletsOfClassType[] = [{
  title: 'arms',
  backgroundImage: `${RESOURCE_URI}/talents/backgrounds/wrath/161.jpg`,
  icon: `${RESOURCE_URI}/icons/large/ability_rogue_eviscerate.jpg`,
  talents: [{
    id: 'warrior_arms_improved_heroic_strike',
    title: 'Improved Heroic Strike',
    description: {
      1: 'Reduces the cost of your Heroic Strike ability by 1 rage point.',
      2: 'Reduces the cost of your Heroic Strike ability by 2 rage points.',
      3: 'Reduces the cost of your Heroic Strike ability by 3 rage points.',
    },
    icon: `${RESOURCE_URI}/icons/large/ability_rogue_ambush.jpg`,
    tier: 1,
    column: 1,
    max: 3,
  }],
}, {
  title: 'fury',
  backgroundImage: `${RESOURCE_URI}/talents/backgrounds/wrath/164.jpg`,
  icon: `${RESOURCE_URI}/icons/large/ability_warrior_innerrage.jpg`,
  talents: [{
    id: 'warrior_fury_armored_to_the_teeth',
    title: 'Armored to the Teeth',
    description: {
      1: 'Increases your attack power by 1 for every 108 armor value you have.',
      2: 'Increases your attack power by 2 for every 108 armor value you have.',
      3: 'Increases your attack power by 3 for every 108 armor value you have.',
    },
    icon: `${RESOURCE_URI}/icons/large/inv_shoulder_22.jpg`,
    tier: 1,
    column: 1,
    max: 3,
  }],
}, {
  title: 'protection',
  backgroundImage: `${RESOURCE_URI}/talents/backgrounds/wrath/163.jpg`,
  icon: `${RESOURCE_URI}/icons/large/inv_shield_06.jpg`,
  talents: [{
    id: 'warrior_protection_improved_bloodrage',
    title: 'Improved Bloodrage',
    description: {
      1: 'Increases the rage generated by your Bloodrage ability by 25%.',
      2: 'Increases the rage generated by your Bloodrage ability by 50%.',
    },
    icon: `${RESOURCE_URI}/icons/large/ability_racial_bloodrage.jpg`,
    tier: 1,
    column: 1,
    max: 2,
  }],
}];
